import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  buttonList: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 60,
    marginBottom: 70,
    width: "100%",
  },
  tutorialWrapper: {
    width: "96%",
    alignItems: "center",
    marginBottom: 28,
  },
  tutorialBlock: {
    backgroundColor: "#1e293b",
    borderRadius: 22,
    padding: 22,
    marginBottom: 14,
    borderWidth: 2,
    borderColor: "#2563eb",
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 13,
    elevation: 10,
    width: "100%",
  },
  tutorialText: {
    color: "#60a5fa",
    fontSize: 17,
    fontWeight: "700",
    marginBottom: 12,
    textAlign: "center",
    textShadowColor: "#1e3a8a",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  tutorialButton: {
    alignSelf: "center",
    borderRadius: 20,
    borderWidth: 2,
    paddingVertical: 8,
    paddingHorizontal: 32,
    backgroundColor: "#2563eb",
    borderColor: "#60a5fa",
    marginTop: 8,
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 7,
    elevation: 4,
  },
  tutorialButtonText: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#f0f9ff",
    textAlign: "center",
    letterSpacing: 0.1,
  },
  fullButton: {
    flex: 1,
    marginVertical: 12,
    alignSelf: "center",
    shadowColor: "#60a5fa",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 5,
  },
  coinButton: {
    position: "absolute",
    bottom: 100,
    left: 28,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 22,
    backgroundColor: "#2563eb",
    borderWidth: 2,
    borderColor: "#60a5fa",
    shadowColor: "#facc15",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  crystalButton: {
    position: "absolute",
    bottom: 28,
    right: 28,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 22,
    backgroundColor: "#2563eb",
    borderWidth: 2,
    borderColor: "#38bdf8",
    shadowColor: "#38bdf8",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 9,
    elevation: 4,
    bottom: 100,
  },
  currencyText: {
    color: "#e0eaff",
    fontSize: 16,
    fontWeight: "700",
    marginLeft: 8,
    textShadowColor: "#0ea5e9",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    letterSpacing: 0.1,
  },
});
